% -------------------------------------------------------------------
%  Generated by MATLAB on 21-Jan-2015 10:32:20
%  MATLAB version: 8.4.0.150421 (R2014b)
% -------------------------------------------------------------------
clear
close all
clc
H = imread('//1a.png');
H = double(H)/255.0;
%1.现实初始图像

imtool(H);
%获取图片长宽
[h,w]=size(H);
min_I=zeros(h,w);
%2.取M(x)为H(x)3通道最小值
M = min(H,[],3);
%3.均值滤波
sv = ceil(max(h,w)/50);
if mod(sv,2)==0
    sv = sv +1;
end
key = fspecial('average',sv);%均值滤波算子
M_ave = imfilter(M,key,'symmetric');

%4.求M(x)中所有元素的均值Mave
[h,w] = size(M_ave);
n = 0.0;  
for i=1:h  
    for j=1:w  
        n = n + M_ave(i, j);    
    end  
end  
Mave = n / (h * w); 
%5.求出L(x)
P = 5.0;%P为调节参数，P越大图像越暗去雾效果越明显
L = min(min(P*Mave,0.9)*M_ave,M);
%求A
temp = max(H,[],3);
A = 0.5 *(max(temp(:)) + max(M_ave(:))) * [1; 1; 1];
%求F
[h, w, s] = size(H);  
F = zeros(h, w, s);  
for i=1:h  
    for j=1:w  
        for k=1:s  
            F(i,j,k) = (H(i,j,k) - L(i,j)) / (1 - L(i,j)/A(k));  
        end  
    end  
end     
imtool(F);
